services:
  app:
    build:
      context: .
      target: base
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"

  cs2:
    image: cm2network/csgo
    stdin_open: true
    tty: true